development:
  adapter: postgresql
  encoding: unicode
  database: ap_development
  pool: 5
  username: ap
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: ap_test
  pool: 5
  username: ap
  password: password1
